In [ ]:
# type: ignore

In [1]:
import sys
sys.path.append('../')
import os
os.environ['PATH'] = os.environ['PATH'] + os.pathsep + '/home/ubuntu/miniconda3/envs/utrtool/bin/'

import pickle as pkl
import pandas as pd

In [ ]:
with open("/mnt/weird_vol/projects/3utr/blood_test/data_inhouse/210708_NB551305_0384_AH2NLFAFX3/utrcalling/intermediate/UTR_sizes_counts_1.pkl", "rb") as input_file:
    counts_1 = pkl.load(input_file)

In [ ]:
counts_1.head(n=3)

In [ ]:
counts_1.ENSG00000188976

In [ ]:
with open("/mnt/weird_vol/projects/3utr/Blood/14Jan/220114_NB551305_0417_AHY3JTBGXK/utrcalling/intermediate/UTR_sizes_counts_merged_intercept.pkl", "rb") as input_file:
    counts_test = pkl.load(input_file)

In [ ]:
with open("/mnt/weird_vol/projects/3utr/blood_test/data_inhouse/210708_NB551305_0384_AH2NLFAFX3/utrcalling/intermediate/UTR_sizes_counts_merged_intercept.pkl", "rb") as input_file:
    counts_previous = pkl.load(input_file)

In [ ]:
counts_test.head(n=3)

In [ ]:
counts_previous.head(n=3)

In [ ]:
counts_test.ENSG00000187608

In [ ]:
counts_previous.ENSG00000187608

In [ ]:
print(len(wt_test), len(wt_test)/5, sep='\n')

In [ ]:
wt_test[wt_test[0:2]]

In [ ]:
len(wt_test[:20])

In [ ]:
for utr in wt_test:
    print(utr)
    break

In [ ]:
data = pd.DataFrame.from_dict(wt_test.__dict__)

In [ ]:
data.head()

In [ ]:
data.shape[0]/5

In [ ]:
data.shape[0]/4438

In [ ]:
S = 4438
N = int(data.shape[0]/4438)
frames = [data.iloc[i*S:(i+1)*S].copy() for i in range(N)]

In [ ]:
frames[4]

In [ ]:
len(frames)

# Merged counts data from 06May

## Merged data

In [ ]:
with open("/mnt/weird_vol/projects/3utr/Blood/06May/utrcalling/intermediate/UTR_sizes_counts_merged_union.pkl", "rb") as input_file:
    counts_merged = pkl.load(input_file)

In [ ]:
counts_merged.head(n=3)

In [ ]:
counts_merged.ENSG00000188976

## Individual samples

In [ ]:
with open("/mnt/weird_vol/projects/3utr/Blood/06May/utrcalling/intermediate/UTR_sizes_counts_1.pkl", "rb") as input_file:
    counts_1 = pkl.load(input_file)

In [ ]:
counts_1.head(n=3)

In [ ]:
counts_1.ENSG00000188976

# Check all_till_06Jul intermediate files

In [2]:
with open("/mnt/weird_vol/projects/3utr/Blood/all_till_06Jul/intermediate/UTR_sizes_counts_64.pkl", "rb") as input_file:
    counts_test = pkl.load(input_file)

In [5]:
with open("/mnt/weird_vol/projects/3utr/Blood/all_till_06Jul/intermediate/UTR_sizes_counts_65.pkl", "rb") as input_file:
    counts_test_65 = pkl.load(input_file)

In [ ]:
with open("/mnt/weird_vol/projects/3utr/Blood/all_till_06Jul/intermediate/UTR_sizes_counts_1_old.pkl", "rb") as input_file:
    counts_test_1_old = pkl.load(input_file)

In [10]:
with open("/mnt/weird_vol/projects/3utr/Blood/all_till_06Jul/intermediate_old/UTR_sizes_counts_78.pkl", "rb") as input_file:
    counts_test_64_oldy = pkl.load(input_file)

In [12]:
with open("/mnt/weird_vol/projects/3utr/Blood/all_till_06Jul/intermediate/UTR_sizes_counts_1.pkl", "rb") as input_file:
    counts_test_1 = pkl.load(input_file)

In [13]:
counts_test_1_exploded = counts_test_1.explode(counts_test_1.columns.to_list())
counts_test_1_exploded

,read_start_positions,read_strands,read_barcodes,read_umis,read_lengths,utr_sizes_from_reads
utr_name,,,,,,
ENSG00000188976,944203,+,CACAGA-1,TCAGGCGG,68,489
ENSG00000188976,944203,+,CACAGA-1,TGATTAGC,66,489
ENSG00000188976,944204,+,CACAGA-1,GGTATGAC,63,488
ENSG00000188976,944206,+,CACAGA-1,TTCACAAA,64,486
ENSG00000188976,944211,+,CACAGA-1,GGTCGGGA,65,481
...,...,...,...,...,...,...
ENSG00000012817,19705426,+,CACAGA-1,CGGACTGG,61,567
ENSG00000012817,19705497,+,CACAGA-1,TGTGAAAC,76,496
ENSG00000012817,19705597,+,CACAGA-1,CTATGTCA,68,396
ENSG00000012817,19705601,+,CACAGA-1,ATTAGGTA,69,392
ENSG00000205916_2,24905433,-,CACAGA-1,ACCAGTTA,11,250

In [14]:
counts_test_1_exploded.read_barcodes = counts_test_1_exploded.read_barcodes.replace({"1": "6"}, regex=True)
counts_test_1_exploded

,read_start_positions,read_strands,read_barcodes,read_umis,read_lengths,utr_sizes_from_reads
utr_name,,,,,,
ENSG00000188976,944203,+,CACAGA-6,TCAGGCGG,68,489
ENSG00000188976,944203,+,CACAGA-6,TGATTAGC,66,489
ENSG00000188976,944204,+,CACAGA-6,GGTATGAC,63,488
ENSG00000188976,944206,+,CACAGA-6,TTCACAAA,64,486
ENSG00000188976,944211,+,CACAGA-6,GGTCGGGA,65,481
...,...,...,...,...,...,...
ENSG00000012817,19705426,+,CACAGA-6,CGGACTGG,61,567
ENSG00000012817,19705497,+,CACAGA-6,TGTGAAAC,76,496
ENSG00000012817,19705597,+,CACAGA-6,CTATGTCA,68,396
ENSG00000012817,19705601,+,CACAGA-6,ATTAGGTA,69,392
ENSG00000205916_2,24905433,-,CACAGA-6,ACCAGTTA,11,250

In [16]:
counts_test_1_corr = counts_test_1_exploded.groupby(level=0).agg(list)
counts_test_1_corr

,read_start_positions,read_strands,read_barcodes,read_umis,read_lengths,utr_sizes_from_reads
utr_name,,,,,,
ENSG00000000003,[100627158],[+],[CACAGA-6],[TTAGCATG],[10],[2827]
ENSG00000000419_4,[50942034],[+],[CACAGA-6],[AACTTGGG],[78],[73]
ENSG00000000457,"[169850977, 169850983, 169850983, 169850984, 1...","[+, +, +, +, +, +]","[CACAGA-6, CACAGA-6, CACAGT-6, CACAGA-6, CACAG...","[AAAGGGCC, GTTGGGAC, GGTCGTCT, TCGGTGCC, TCAAA...","[35, 29, 30, 29, 28, 64]","[2734, 2728, 2728, 2727, 2658, 618]"
ENSG00000000938,"[27612063, 27612063, 27612064, 27612243, 27612...","[+, +, +, +, +, +, +, +, +, +, +, +, +, +, +, ...","[CACAGA-6, CACAGA-6, CACAGA-6, CACAGA-6, CACAG...","[GGAACGCC, ATTGTACG, TAAACGAA, GCCGATGG, TGAGG...","[68, 61, 66, 10, 88, 67, 65, 87, 68, 69, 59, 6...","[849, 849, 848, 669, 629, 627, 627, 627, 624, ..."
ENSG00000001036,"[143495476, 143495476, 143495481, 143495486, 1...","[+, +, +, +, +, +, +, +]","[CACAGA-6, CACAGA-6, CACAGA-6, CACAGA-6, CACAG...","[GTAGCTCA, GAAATACC, TGACGAAC, ACGTCCTG, CCATT...","[66, 67, 64, 64, 64, 66, 63, 60]","[229, 229, 224, 219, 217, 217, 216, 213]"
...,...,...,...,...,...,...
ENSG00000288675,"[798420, 798491, 798850]","[-, -, -]","[CACAGA-6, CACAAA-6, CACAGA-6]","[CTCTTTCG, ACGGGAAC, GTTCCAAC]","[16, 11, 22]","[147, 218, 577]"
ENSG00000288701,"[131496339, 131496338, 131496337, 131496337, 1...","[-, -, -, -, -, -, -, -, -, -, -, -, -, -, -, ...","[CACAGA-6, CACAGA-6, CACAGA-6, CACAGA-6, CACAG...","[CTCTGTTG, GGTGGCGG, TGCCGTTG, GGTCGCGG, TGTTC...","[90, 87, 85, 83, 85, 83, 86, 83, 91, 86, 86, 8...","[557, 556, 555, 555, 558, 555, 558, 555, 564, ..."
ENSG00000288710_2,"[49012367, 49012375, 49012683]","[+, +, +]","[CACAGA-6, CACAGA-6, CACAGA-6]","[TTATTCTG, CGGGACGA, AAGGATTC]","[91, 86, 71]","[742, 734, 426]"
ENSG00000288721,[41802514],[+],[CACAAA-6],[TTTTTGAG],[24],[1495]
ENSG00000288722,"[154888057, 154888051, 154888042, 154888057, 1...","[-, -, -, -, -, -, -, -]","[CACAGA-6, CACAGA-6, CACAGA-6, CACAGA-6, CACAG...","[GACGGTTG, GTTTCTCC, TGGAGGCC, GTGCTGTC, GAGAT...","[69, 63, 51, 66, 66, 69, 48, 41]","[567, 561, 552, 567, 567, 570, 550, 545]"

In [ ]:
counts_test_1_corr.to_pickle("/mnt/weird_vol/projects/3utr/Blood/all_till_06Jul/intermediate/UTR_sizes_counts_1.pkl")