In [1]:
import anndata
import pickle as pkl

/home/ubuntu/miniconda3/envs/utrtool/lib/python3.9/site-packages/anndata/core/anndata.py:17: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex

In [2]:
def add_to_peaks_var(peak_var, annotations):
    annotations['utr_name'] = annotations.index

    peak_var_new = peak_var.copy(deep=True)
    peak_var_new['utr_name'] = peak_var_new.index.str.split(pat=r"-").str[0]

    peak_var_new = peak_var_new.join(
        annotations, on='utr_name', how='left', rsuffix='_right')

    peak_var_new = peak_var_new.drop('utr_name_right', axis=1)

    return peak_var_new


def generate_count_matrix_anndata(count_matrix, var, obs=None):
    count_matrix_anndata = anndata.AnnData(count_matrix, var=var, obs=obs)
    return count_matrix_anndata

In [3]:
with open("/mnt/weird_vol/projects/3utr/wildtypes_analysis/intermediate/peaks_count_matrix_intercept.pkl", "rb") as input_file:
    counts = pkl.load(input_file)

with open("/mnt/weird_vol/projects/3utr/wildtypes_analysis/intermediate/peaks_obs_intercept.pkl", "rb") as input_file:
    obs = pkl.load(input_file)

with open("/mnt/weird_vol/projects/3utr/wildtypes_analysis/intermediate/peaks_var_intercept.pkl", "rb") as input_file:
    var = pkl.load(input_file)

with open("/mnt/weird_vol/projects/3utr/wildtypes_analysis/intermediate/UTR_reference_subset_intercept.pkl", "rb") as input_file:
    reference = pkl.load(input_file)

In [ ]:
count_matrix_anndata = anndata.AnnData(counts, var=var, obs=obs)

In [5]:
print(
    counts.shape,
    obs.shape,
    var.shape
)

(16065, 8) (16065, 2) (221115, 1)

In [8]:
counts

,ENSMUSG00000051951-1,ENSMUSG00000051951-2,ENSMUSG00000051951-3,ENSMUSG00000051951-4,ENSMUSG00000051951-5,ENSMUSG00000051951-6,ENSMUSG00000051951-7,ENSMUSG00000051951-8
AGGGTTTTCTGGGAGA-6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GGAGATGAGACACACG-4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CAACAGTGTACTAGCT-4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GATCAGTCACGCTGTG-6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AGCGTATGTGGCAAAC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
TTTGACTTCCACGAAT-6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GAAATGATCCTCACTG-6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GAGGTGAAGGACCACA-2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GTCATCCCAGAATCGG-6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CGTGCTTAGCCTCTGG-4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
var

                          utr_size
ENSMUSG00000051951-1         202.0
ENSMUSG00000051951-2         496.0
ENSMUSG00000051951-3         585.0
ENSMUSG00000051951-4         732.0
ENSMUSG00000051951-5         879.0
...                            ...
ENSMUSG00000069045_11-6       56.0
ENSMUSG00000069045_11-7       70.0
ENSMUSG00000069045_11-8       80.0
ENSMUSG00000069045_11-9      110.0
ENSMUSG00000069045_11-10     120.0

[221115 rows x 1 columns]