In [1]:
import sys
sys.path.append('../')
import os
os.environ['PATH'] = os.environ['PATH'] + os.pathsep + '/home/ubuntu/miniconda3/envs/utrtool/bin/'

import pybedtools
import HTSeq

from core import utr_reference as utr_ref

In [2]:
five_gtf_path = "../tests/test_data/test_mus_musculus_GRCm38_102_5prime.gtf.gz"
five_gtf_file = utr_ref.open_gtf(five_gtf_path)
three_gtf_path = "../tests/test_data/test_mus_musculus_GRCm38_102.gtf.gz"
three_gtf_file = utr_ref.open_gtf(three_gtf_path)

INFO:root:Extracted GTF attributes: ['gene_id', 'gene_version', 'transcript_id', 'transcript_version', 'exon_number', 'gene_name', 'gene_source', 'gene_biotype', 'havana_gene', 'havana_gene_version', 'transcript_name', 'transcript_source', 'transcript_biotype', 'tag', 'ccds_id', 'protein_id', 'protein_version', 'transcript_support_level', 'exon_id', 'exon_version', 'havana_transcript', 'havana_transcript_version']
INFO:root:Extracted GTF attributes: ['gene_id', 'gene_version', 'transcript_id', 'transcript_version', 'exon_number', 'gene_name', 'gene_source', 'gene_biotype', 'havana_gene', 'havana_gene_version', 'transcript_name', 'transcript_source', 'transcript_biotype', 'protein_id', 'protein_version', 'tag', 'transcript_support_level', 'ccds_id', 'exon_id', 'exon_version', 'havana_transcript', 'havana_transcript_version']

In [3]:
five_gtf_file

,seqname,source,feature,start,end,score,strand,frame,gene_id,gene_version,...,transcript_biotype,tag,ccds_id,protein_id,protein_version,transcript_support_level,exon_id,exon_version,havana_transcript,havana_transcript_version
0,1,ensembl,CDS,173935010,173935177,NaN,-,0,ENSMUSG00000039997,16,...,protein_coding,"CCDS,basic",CCDS35793,ENSMUSP00000079976,5,1,,,,
1,1,ensembl,exon,34293320,34293483,NaN,+,0,ENSMUSG00000026131,20,...,protein_coding,basic,,,,5,ENSMUSE00001373212,1,,
2,1,ensembl,exon,75240892,75240984,NaN,+,0,ENSMUSG00000026203,16,...,protein_coding,"CCDS,basic",CCDS15068,,,5,ENSMUSE00000629572,1,,
3,1,ensembl,exon,88259119,88259221,NaN,+,0,ENSMUSG00000079429,9,...,protein_coding,basic,,,,5,ENSMUSE00000694391,1,,
4,1,ensembl,five_prime_utr,135840861,135840874,NaN,+,0,ENSMUSG00000026414,13,...,protein_coding,basic,,,,5,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1991,Y,havana,exon,29588099,29588167,NaN,-,0,ENSMUSG00000101412,6,...,lincRNA,,,,,5,ENSMUSE00001333508,1,OTTMUST00000125780,1
1992,Y,havana,five_prime_utr,10146582,10146768,NaN,-,0,ENSMUSG00000095032,2,...,protein_coding,basic,,,,1,,,OTTMUST00000121386,1
1993,Y,havana,five_prime_utr,55731756,55731799,NaN,+,0,ENSMUSG00000095135,7,...,protein_coding,basic,,,,1,,,OTTMUST00000124643,1
1994,Y,havana,transcript,31290381,31292742,NaN,+,0,ENSMUSG00000099855,6,...,lincRNA,,,,,1,,,OTTMUST00000125551,1
1995,Y,havana,transcript,82162737,82163432,NaN,-,0,ENSMUSG00000100438,1,...,unprocessed_pseudogene,basic,,,,NA,,,OTTMUST00000121370,1

In [4]:
three_gtf_file

,seqname,source,feature,start,end,score,strand,frame,gene_id,gene_version,...,transcript_biotype,protein_id,protein_version,tag,transcript_support_level,ccds_id,exon_id,exon_version,havana_transcript,havana_transcript_version
0,1,ensembl,CDS,118467880,118467977,NaN,+,0,ENSMUSG00000064302,13,...,protein_coding,ENSMUSP00000042266,6,basic,5,,,,,
1,1,ensembl,CDS,126124043,126124111,NaN,-,0,ENSMUSG00000049690,15,...,protein_coding,ENSMUSP00000092192,3,"CCDS,basic",5,CCDS48346,,,,
2,1,ensembl,CDS,165875741,165876048,NaN,-,2,ENSMUSG00000026565,18,...,protein_coding,ENSMUSP00000107056,2,"CCDS,basic",2,CCDS35761,,,,
3,1,ensembl,exon,132114764,132114970,NaN,-,0,ENSMUSG00000026437,11,...,protein_coding,,,"CCDS,basic",1,CCDS15281,ENSMUSE00000904724,1,,
4,1,ensembl,three_prime_utr,130697017,130697884,NaN,-,0,ENSMUSG00000026409,14,...,protein_coding,,,"CCDS,basic",1,CCDS35701,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,X,havana,transcript,16379396,16379647,NaN,-,0,ENSMUSG00000083551,1,...,processed_pseudogene,,,basic,NA,,,,OTTMUST00000041112,1
1996,X,havana,transcript,92593809,92595368,NaN,+,0,ENSMUSG00000080737,1,...,processed_pseudogene,,,basic,NA,,,,OTTMUST00000043394,1
1997,Y,havana,exon,71407703,71407889,NaN,+,0,ENSMUSG00000101713,1,...,lincRNA,,,,5,,ENSMUSE00001322170,1,OTTMUST00000120253,1
1998,Y,havana,exon,74040628,74040845,NaN,-,0,ENSMUSG00000099685,6,...,processed_transcript,,,basic,5,,ENSMUSE00001329721,1,OTTMUST00000120549,1
1999,Y,havana,three_prime_utr,1224497,1224546,NaN,-,0,ENSMUSG00000068457,14,...,nonsense_mediated_decay,,,,1,,,,OTTMUST00000081744,1

In [5]:
utr = utr_ref.extract_feature(five_gtf_path, 'five_prime_utr')
utr

2021-07-12 16:39:34,880 - INFO - Parsing GTF reference file to retrieve only the UTR annotations
INFO:root:Extracted GTF attributes: ['gene_id', 'gene_version', 'transcript_id', 'transcript_version', 'exon_number', 'gene_name', 'gene_source', 'gene_biotype', 'havana_gene', 'havana_gene_version', 'transcript_name', 'transcript_source', 'transcript_biotype', 'tag', 'ccds_id', 'protein_id', 'protein_version', 'transcript_support_level', 'exon_id', 'exon_version', 'havana_transcript', 'havana_transcript_version']
2021-07-12 16:39:34,965 - INFO - Finished parsing GTF file

,seqname,source,feature,start,end,score,strand,frame,gene_id,gene_version,...,transcript_biotype,tag,ccds_id,protein_id,protein_version,transcript_support_level,exon_id,exon_version,havana_transcript,havana_transcript_version
4,1,ensembl,five_prime_utr,135840861,135840874,NaN,+,0,ENSMUSG00000026414,13,...,protein_coding,basic,,,,5,,,,
5,1,ensembl,five_prime_utr,93489128,93489145,NaN,+,0,ENSMUSG00000116048,1,...,protein_coding,"CCDS,basic",CCDS15190,,,5,,,,
25,1,ensembl_havana,five_prime_utr,10045076,10045085,NaN,+,0,ENSMUSG00000056763,16,...,protein_coding,"CCDS,basic",CCDS35511,,,1,,,OTTMUST00000067846,2
26,1,ensembl_havana,five_prime_utr,110977247,110977363,NaN,-,0,ENSMUSG00000047216,8,...,protein_coding,"CCDS,basic",CCDS35687,,,1,,,OTTMUST00000124945,1
27,1,ensembl_havana,five_prime_utr,119642657,119642658,NaN,-,0,ENSMUSG00000026383,14,...,protein_coding,"CCDS,basic",CCDS15226,,,1,,,OTTMUST00000125203,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1983,X,havana,five_prime_utr,7885749,7885873,NaN,+,0,ENSMUSG00000031156,18,...,protein_coding,"cds_end_NF,mRNA_end_NF",,,,5,,,OTTMUST00000146359,1
1984,X,havana,five_prime_utr,93968659,93969930,NaN,+,0,ENSMUSG00000081044,8,...,protein_coding,basic,,,,1,,,OTTMUST00000043486,2
1988,Y,ensembl_havana,five_prime_utr,1454608,1454684,NaN,-,0,ENSMUSG00000069044,6,...,protein_coding,"CCDS,basic",CCDS30544,,,1,,,OTTMUST00000064932,2
1992,Y,havana,five_prime_utr,10146582,10146768,NaN,-,0,ENSMUSG00000095032,2,...,protein_coding,basic,,,,1,,,OTTMUST00000121386,1
1993,Y,havana,five_prime_utr,55731756,55731799,NaN,+,0,ENSMUSG00000095135,7,...,protein_coding,basic,,,,1,,,OTTMUST00000124643,1

In [6]:
utr = utr.sort_values(by=['seqname', 'start'])
annotations = ['gene_id', 'score', 'strand', 'transcript_id', 'gene_name']
ann_cols, ann_idx = utr_ref.prepare_annotations_index(annotations)
utr_bed = pybedtools.BedTool.from_dataframe(utr, columns=ann_cols)
utr_reduced = utr_ref.reduce_regions(utr_bed, annotations_index=ann_idx)

2021-07-12 16:39:35,021 - INFO - Merging overlapping UTR regions

In [7]:
utr

,seqname,source,feature,start,end,score,strand,frame,gene_id,gene_version,...,transcript_biotype,tag,ccds_id,protein_id,protein_version,transcript_support_level,exon_id,exon_version,havana_transcript,havana_transcript_version
42,1,ensembl_havana,five_prime_utr,7088920,7089216,NaN,+,0,ENSMUSG00000051285,17,...,protein_coding,"CCDS,basic",CCDS35508,,,1,,,OTTMUST00000113805,2
47,1,ensembl_havana,five_prime_utr,9827013,9827119,NaN,+,0,ENSMUSG00000025915,14,...,protein_coding,"CCDS,basic",CCDS14816,,,1,,,OTTMUST00000118856,2
25,1,ensembl_havana,five_prime_utr,10045076,10045085,NaN,+,0,ENSMUSG00000056763,16,...,protein_coding,"CCDS,basic",CCDS35511,,,1,,,OTTMUST00000067846,2
29,1,ensembl_havana,five_prime_utr,12692277,12692684,NaN,+,0,ENSMUSG00000016918,15,...,protein_coding,"CCDS,basic",CCDS14820,,,1,,,OTTMUST00000123376,1
98,1,havana,five_prime_utr,36307733,36307832,NaN,+,0,ENSMUSG00000037447,16,...,protein_coding,"cds_end_NF,mRNA_end_NF",,,,2,,,OTTMUST00000051020,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941,X,ensembl_havana,five_prime_utr,164072083,164072227,NaN,-,0,ENSMUSG00000040749,11,...,protein_coding,"CCDS,basic",CCDS30516,,,1,,,OTTMUST00000046617,1
1975,X,havana,five_prime_utr,164250282,164250368,NaN,-,0,ENSMUSG00000031377,11,...,protein_coding,basic,,,,5,,,OTTMUST00000046572,2
1988,Y,ensembl_havana,five_prime_utr,1454608,1454684,NaN,-,0,ENSMUSG00000069044,6,...,protein_coding,"CCDS,basic",CCDS30544,,,1,,,OTTMUST00000064932,2
1992,Y,havana,five_prime_utr,10146582,10146768,NaN,-,0,ENSMUSG00000095032,2,...,protein_coding,basic,,,,1,,,OTTMUST00000121386,1
1993,Y,havana,five_prime_utr,55731756,55731799,NaN,+,0,ENSMUSG00000095135,7,...,protein_coding,basic,,,,1,,,OTTMUST00000124643,1

In [8]:
utr_bed.head()

1	7088920	7089216	ENSMUSG00000051285	.	+	ENSMUST00000061280	Pcmtd1
 1	9827013	9827119	ENSMUSG00000025915	.	+	ENSMUST00000168907	Sgk3
 1	10045076	10045085	ENSMUSG00000056763	.	+	ENSMUST00000071087	Cspp1
 1	12692277	12692684	ENSMUSG00000016918	.	+	ENSMUST00000177608	Sulf1
 1	36307733	36307832	ENSMUSG00000037447	.	+	ENSMUST00000126413	Arid5a
 1	36367984	36368034	ENSMUSG00000010453	.	-	ENSMUST00000010597	Kansl3
 1	36534291	36534437	ENSMUSG00000067653	.	-	ENSMUST00000193083	Ankrd23
 1	38987865	38988069	ENSMUSG00000026078	.	+	ENSMUST00000194552	Pdcl3
 1	39577275	39577405	ENSMUSG00000048234	.	-	ENSMUST00000062525	Rnf149
 1	43098710	43098763	ENSMUSG00000010290	.	+	ENSMUST00000010434	AI597479

In [9]:
utr_reduced.head()

1	7088920	7089216	ENSMUSG00000051285	.	+	ENSMUST00000061280	Pcmtd1
 1	9827013	9827119	ENSMUSG00000025915	.	+	ENSMUST00000168907	Sgk3
 1	10045076	10045085	ENSMUSG00000056763	.	+	ENSMUST00000071087	Cspp1
 1	12692277	12692684	ENSMUSG00000016918	.	+	ENSMUST00000177608	Sulf1
 1	36307733	36307832	ENSMUSG00000037447	.	+	ENSMUST00000126413	Arid5a
 1	36367984	36368034	ENSMUSG00000010453	.	-	ENSMUST00000010597	Kansl3
 1	36534291	36534437	ENSMUSG00000067653	.	-	ENSMUST00000193083	Ankrd23
 1	38987865	38988069	ENSMUSG00000026078	.	+	ENSMUST00000194552	Pdcl3
 1	39577275	39577405	ENSMUSG00000048234	.	-	ENSMUST00000062525	Rnf149
 1	43098710	43098763	ENSMUSG00000010290	.	+	ENSMUST00000010434	AI597479

In [10]:
utr_reduced = utr_ref.generate_utr_name(utr_reduced)
utr_reduced.head()

,chrom,start,end,name,score,strand,thickStart,thickEnd
utr_name,,,,,,,,
ENSMUSG00000051285,1,7088920,7089216,ENSMUSG00000051285,.,+,ENSMUST00000061280,Pcmtd1
ENSMUSG00000025915,1,9827013,9827119,ENSMUSG00000025915,.,+,ENSMUST00000168907,Sgk3
ENSMUSG00000056763,1,10045076,10045085,ENSMUSG00000056763,.,+,ENSMUST00000071087,Cspp1
ENSMUSG00000016918,1,12692277,12692684,ENSMUSG00000016918,.,+,ENSMUST00000177608,Sulf1
ENSMUSG00000037447,1,36307733,36307832,ENSMUSG00000037447,.,+,ENSMUST00000126413,Arid5a

In [11]:
utr_reduced = utr_ref.correct_column_names(utr_reduced)
utr_reduced

,chrom,start,end,name,score,strand,transcript_id,gene_name
utr_name,,,,,,,,
ENSMUSG00000051285,1,7088920,7089216,ENSMUSG00000051285,.,+,ENSMUST00000061280,Pcmtd1
ENSMUSG00000025915,1,9827013,9827119,ENSMUSG00000025915,.,+,ENSMUST00000168907,Sgk3
ENSMUSG00000056763,1,10045076,10045085,ENSMUSG00000056763,.,+,ENSMUST00000071087,Cspp1
ENSMUSG00000016918,1,12692277,12692684,ENSMUSG00000016918,.,+,ENSMUST00000177608,Sulf1
ENSMUSG00000037447,1,36307733,36307832,ENSMUSG00000037447,.,+,ENSMUST00000126413,Arid5a
...,...,...,...,...,...,...,...,...
ENSMUSG00000040749,X,164072083,164072227,ENSMUSG00000040749,.,-,ENSMUST00000071667,Siah1b
ENSMUSG00000031377,X,164250282,164250368,ENSMUSG00000031377,.,-,ENSMUST00000112263,Bmx
ENSMUSG00000069044,Y,1454608,1454684,ENSMUSG00000069044,.,-,ENSMUST00000091188,Usp9y
ENSMUSG00000095032,Y,10146582,10146768,ENSMUSG00000095032,.,-,ENSMUST00000189630,Gm21310
ENSMUSG00000095135,Y,55731756,55731799,ENSMUSG00000095135,.,+,ENSMUST00000185713,Gm21858

In [12]:
len(utr_reduced.index.values)

1030

In [23]:
utr_reduced.to_pickle('../tests/test_data/test_UTR_reference_5prime.pkl')

In [13]:
from core import utr_mapping, protocols

In [14]:
intervals = utr_mapping.generate_utr_intervals(utr_reduced)
ct = 0
for name, interval in intervals.items():
    print(name, interval, interval.start_d, sep=': ')
    ct += 1
    if ct == 5:
        break

Generating genomic interval for UTR number: 1030it [00:00, 303124.69it/s]ENSMUSG00000051285: 1:[7088919,7089216)/+: 7088919
ENSMUSG00000025915: 1:[9827012,9827119)/+: 9827012
ENSMUSG00000056763: 1:[10045075,10045085)/+: 10045075
ENSMUSG00000016918: 1:[12692276,12692684)/+: 12692276
ENSMUSG00000037447: 1:[36307732,36307832)/+: 36307732

In [15]:
alignments = "../tests/test_data/test_CapPhospho_genome_102_coordsort.bam"
protocol = protocols.Protocol(platform='smart-seq_cap', version=3)
read_mappings = utr_mapping.map_reads_to_utr(alignments, intervals, read='first', protocol=protocol, sample='control')

2021-07-12 16:39:35,362 - INFO - Protocol args:

2021-07-12 16:39:35,364 - INFO - Function to get read information: <function Protocol.get_reads_identity_smart_seq_3_cap at 0x7f0586fa3af0>

2021-07-12 16:39:35,364 - INFO - Function to check if strand matches: <function Protocol.check_strand_matches_smart_seq at 0x7f0586fa3c10>

2021-07-12 16:39:35,365 - INFO - Position counts merging method: union

2021-07-12 16:39:35,366 - INFO - Extracting reads from ../tests/test_data/test_CapPhospho_genome_102_coordsort.bam and mapping them to the reference UTR
Mapping reads to reference UTR number: 100%|██████████| 1030/1030 [00:00<00:00, 17339.97it/s]
2021-07-12 16:39:35,432 - DEBUG - Size of mapped reads object in bytes: 61456

Memory usage:20.1

In [16]:
read_mappings

UtrMappings(utr_ids=['ENSMUSG00000033953', 'ENSMUSG00000041231', 'ENSMUSG00000039850', 'ENSMUSG00000020601', 'ENSMUSG00000076432', 'ENSMUSG00000005982', 'ENSMUSG00000023905', 'ENSMUSG00000037089', 'ENSMUSG00000023944', 'ENSMUSG00000034868_2', 'ENSMUSG00000039770', 'ENSMUSG00000024843', 'ENSMUSG00000024906', 'ENSMUSG00000024926', 'ENSMUSG00000026767', 'ENSMUSG00000027168', 'ENSMUSG00000003662', 'ENSMUSG00000027560', 'ENSMUSG00000028044', 'ENSMUSG00000055436', 'ENSMUSG00000006699', 'ENSMUSG00000040952', 'ENSMUSG00000037563', 'ENSMUSG00000035642', 'ENSMUSG00000025485', 'ENSMUSG00000058454', 'ENSMUSG00000005413', 'ENSMUSG00000034424', 'ENSMUSG00000007815', 'ENSMUSG00000095041', 'ENSMUSG00000031167'], _index=0, read_start_positions=[[17159350], [44470494], [119491380], [15816067], [21417531, 21417531, 21417538, 21417559, 21417588], [3884699, 3884699], [23677423, 23677444, 23677448], [45563935, 45563958, 45563984], [45573262, 45573265, 45573265, 45573265, 45573265, 45573265, 45573265, 45573266], [70990515, 70990525, 70990556, 70990539], [72836706], [3851837], [5488276], [5610044], [12419434], [105674582], [127247759], [170731889], [89418258, 89418265, 89418265, 89418277, 89418292], [158036605], [137357676, 137357676, 137357676, 137357680, 137357700, 137357713], [24884590, 24884592, 24884592, 24884592, 24884603, 24884620, 24884620, 24884626, 24884632, 24884632, 24884653, 24884632, 24884632, 24884632, 24884632, 24884633, 24884632, 24884632, 24884632, 24884642, 24884632, 24884632, 24884632, 24884632, 24884632, 24884632, 24884644, 24884632, 24884632, 24884632, 24884633, 24884633, 24884633, 24884633, 24884633, 24884634, 24884637, 24884635, 24884637, 24884656, 24884637, 24884639, 24884643], [28350733, 28350748, 28350748, 28350748, 28350748, 28350748, 28350748, 28350748, 28350748, 28350748, 28350748, 28350749, 28350749, 28350749, 28350749, 28350749, 28350749, 28350749, 28350749, 28350749, 28350750, 28350750, 28350774, 28350766, 28350750, 28350750, 28350750, 28350750, 28350750, 28350750, 28350750, 28350752, 28350768, 28350753, 28350753, 28350751, 28350751, 28350753, 28350754, 28350791], [97579428], [140857394], [143830213, 143830222, 143830222, 143830242], [75093620, 75093620, 75093621, 75093621, 75093621], [116993497], [108306358, 108306358, 108306363, 108306381, 108306388, 108306398, 108306444, 108306445], [59662], [8145696, 8145696, 8145699, 8145750]], read_strands=[['+'], ['-'], ['+'], ['-'], ['-', '-', '-', '-', '-'], ['+', '+'], ['-', '-', '-'], ['+', '+', '+'], ['-', '-', '-', '-', '-', '-', '-', '-'], ['-', '-', '-', '-'], ['+'], ['+'], ['-'], ['-'], ['-'], ['+'], ['-'], ['+'], ['-', '-', '-', '-', '-'], ['-'], ['-', '-', '-', '-', '-', '-'], ['+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], ['+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], ['-'], ['+'], ['+', '+', '+', '+'], ['+', '+', '+', '+', '+'], ['-'], ['+', '+', '+', '+', '+', '+', '+', '+'], ['-'], ['-', '-', '-', '-']], read_barcodes=[['control'], ['control'], ['control'], ['control'], ['control', 'control', 'control', 'control', 'control'], ['control', 'control'], ['control', 'control', 'control'], ['control', 'control', 'control'], ['control', 'control', 'control', 'control', 'control', 'control', 'control', 'control'], ['control', 'control', 'control', 'control'], ['control'], ['control'], ['control'], ['control'], ['control'], ['control'], ['control'], ['control'], ['control', 'control', 'control', 'control', 'control'], ['control'], ['control', 'control', 'control', 'control', 'control', 'control'], ['control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control'], ['control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control'], ['control'], ['control'], ['control', 'control', 'control', 'control'], ['control', 'control', 'control', 'control', 'control'], ['control'], ['control', 'control', 'control', 'control', 'control', 'control', 'control', 'control'], ['control'], ['control', 'control', 'control', 'control']], read_umis=[['TAGGTAGT'], ['CCCAGCTA'], ['TTACCTTC'], ['ACTAAAGG'], ['GAAGACCG', 'CGCCACTA', 'AGCTAAAG', 'ACTGCTGT', 'CACGCCCC'], ['CACGCGGG', 'TTCCATTC'], ['CGCCAGGC', 'GACACGAT', 'AAGGGGAC'], ['ACCCGCCT', 'CCCACATG', 'CCGCGTAG'], ['CCGCCTTT', 'CACCAAGC', 'CCACTAAG', 'ATACACTC', 'CAGGTTTT', 'CCTTTGTT', 'GGTCAGGT', 'AACTTCTT'], ['GCTTTCCT', 'CGCCAACC', 'GTCTGGTC', 'CGCTAACA'], ['CCCAAACT'], ['CTAGCGCG'], ['ACTGGGTG'], ['GCACAGGG'], ['CGCCGCCA'], ['GCTTAACT'], ['ACCGTCAG'], ['CACAGCCG'], ['TGAGGAGG', 'CCTGCAAT', 'CCCCCAGT', 'CGCTCAGT', 'CCCACCAG'], ['GGTAGGTG'], ['AGCCAGGC', 'CTCGCAGC', 'CACACAAC', 'TGGGTTAG', 'CACTACAG', 'CCATGAGG'], ['CCACTTAC', 'GAGAGGAG', 'CAAGGGAC', 'GAAACGGG', 'CCTGCGGG', 'TCAACAAC', 'ACTAGGAC', 'ATCGGGAT', 'GACAATGC', 'CACCGAGG', 'ATGCGCGT', 'GCAGCAGG', 'GTACCACC', 'CCCGCGTA', 'ACCAAAGC', 'TATCCACC', 'TAGACACT', 'GATGACCC', 'GACACCGC', 'GCAATTTC', 'CGGTAACT', 'CGTGTAGG', 'CGGCCACC', 'GCAGATGA', 'GCACAGAC', 'GCAACCAG', 'AAAGGGCT', 'GCCAGCAC', 'CACTATCG', 'ACACCTAC', 'AATACCCC', 'TCCGCTTG', 'ATTTACGC', 'CCATAGGC', 'ATACAACT', 'CAAAACCC', 'GCACCTCG', 'GAGCCCCC', 'CTTTACAG', 'AGGTCACC', 'CAATGACC', 'AGCCTTTC', 'TTTCTCCG'], ['ACCGGAAG', 'CACCCAAT', 'GGCATCAC', 'ACAGTGCT', 'TCACCCAG', 'TGCACGGG', 'CTCTCAAC', 'CCAATGAG', 'GCCACCAC', 'CAGCGGAT', 'CCACTAAC', 'ATGACCCC', 'CCCTCGAC', 'CTTACCGG', 'ACCTTCCA', 'TAACCCTC', 'GCCGGATG', 'CCCAGCAG', 'CCCAGTTC', 'GCCAGGCC', 'GACCAGGG', 'TTCCCTGG', 'TAGCCACC', 'AAAAGTTC', 'CCTTTGAC', 'GAAACCAG', 'TTACAGCC', 'CCGCGGAA', 'ACAGGCCC', 'CATTGGGA', 'CACGCAGG', 'TTACAGGG', 'CTTATCGG', 'CTTCCAGA', 'TAATCAAC', 'TGTAAGGC', 'CCGCCCCC', 'AAGATAAG', 'GGCAACCT', 'ACGCCGCG'], ['GATCCAGC'], ['CCCCCCAG'], ['CTAACGTG', 'CGTGCAAC', 'GCGTTGGA', 'AGCCCAGG'], ['GTTCCGAG', 'GGCTTGAG', 'TAACGCGG', 'ACGCTGCG', 'ACTATGCC'], ['TCCCAACT'], ['CGCTACGG', 'AGCCACGT', 'CAGCCAAG', 'GTGCGGCT', 'GCGTAAAG', 'ACGCACGG', 'AGCCTCTC', 'TCGACGCA'], ['GGAGAGTC'], ['GACGCCAC', 'GCCCCATC', 'TAAAGGAC', 'TAGGCAAG']], read_lengths=[[79], [82], [82], [82], [82, 82, 82, 79, 82], [82, 82], [81, 82, 82], [80, 82, 81], [81, 82, 82, 82, 82, 82, 82, 80], [81, 82, 82, 60], [81], [69], [81], [81], [81], [82], [81], [82], [81, 82, 81, 82, 81], [81], [82, 82, 81, 81, 82, 82], [77, 82, 78, 82, 67, 81, 78, 82, 82, 82, 61, 82, 82, 82, 82, 81, 82, 82, 82, 72, 82, 82, 82, 82, 82, 82, 70, 82, 82, 82, 82, 81, 82, 82, 82, 82, 80, 81, 79, 61, 80, 79, 82], [82, 80, 81, 81, 81, 81, 81, 81, 81, 81, 80, 82, 82, 82, 82, 82, 82, 77, 82, 80, 82, 82, 57, 66, 82, 82, 82, 82, 82, 82, 82, 81, 65, 80, 80, 82, 82, 78, 82, 81], [72], [79], [81, 81, 82, 82], [81, 81, 81, 81, 81], [81], [80, 80, 81, 82, 80, 82, 81, 82], [77], [82, 82, 77, 81]], utr_sizes_from_reads=[[88], [3], [6], [717], [105, 105, 98, 77, 48], [17, 17], [44, 23, 19], [62, 85, 111], [8, 5, 5, 5, 5, 5, 5, 4], [374, 364, 333, 350], [254], [41], [8], [192], [17], [2723], [56], [83], [124, 117, 117, 105, 90], [9], [43, 43, 43, 39, 19, 6], [220, 222, 222, 222, 233, 250, 250, 256, 262, 262, 283, 262, 262, 262, 262, 263, 262, 262, 262, 272, 262, 262, 262, 262, 262, 262, 274, 262, 262, 262, 263, 263, 263, 263, 263, 264, 267, 265, 267, 286, 267, 269, 273], [82, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 98, 98, 98, 98, 98, 98, 98, 98, 98, 99, 99, 123, 115, 99, 99, 99, 99, 99, 99, 99, 101, 117, 102, 102, 100, 100, 102, 103, 140], [53], [438], [75, 84, 84, 104], [0, 0, 1, 1, 1], [39], [230, 230, 235, 253, 260, 270, 316, 317], [4], [183, 183, 180, 129]])

In [21]:
read_mappings.ENSMUSG00000023905

MappedReadInformation(utr_name='ENSMUSG00000023905', read_start_positions=[23677423, 23677444, 23677448], read_strands=['-', '-', '-'], read_barcodes=['control', 'control', 'control'], read_umis=['CGCCAGGC', 'GACACGAT', 'AAGGGGAC'], read_lengths=[81, 82, 82], utr_sizes_from_reads=[44, 23, 19])

In [22]:
len(read_mappings)

31

In [18]:
print(intervals['ENSMUSG00000007815'])

9:[108306128,108306553)/+

In [19]:
bam_file = HTSeq.BAM_Reader(alignments)

In [20]:
for alignment in bam_file[intervals['ENSMUSG00000007815']]:
    print(alignment.iv, alignment.pe_which)

9:[108306358,108306438)/+ first
9:[108306358,108306438)/+ first
9:[108306363,108306444)/+ first
9:[108306381,108306463)/+ first
9:[108306388,108306468)/+ first
9:[108306398,108306480)/+ first
9:[108306444,108306525)/+ first
9:[108306445,108306527)/+ first